@include('_components.matrix.types.image', ['type' => 'fill_width'])
@include('_components.matrix.types.body')
@include('_components.matrix.types.image', ['type' => 'inset_center'])
@include('_components.matrix.types.body')
@include('_components.matrix.types.quote')
@include('_components.matrix.types.body')
@include('_components.matrix.types.image', ['type' => 'outset_left'])
@include('_components.matrix.types.body')
@include('_components.matrix.types.body')
@include('_components.matrix.types.cta')
@include('_components.matrix.types.image', ['type' => 'outset_center'])
@include('_components.matrix.types.body')
